
klasa_3AP = {
    '31': 'KEBAB BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO OSTRY'
}


osoba = {
    '0': 'Imie Nazwisko',
    '31': 'Filip Zych',
}

print(osoba)