
klasa_3AP = {

    '31': 'KEBAB BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO BARDZO OSTRY'

    '25': 'lazania',

}


osoba = {
    '0': 'Imie Nazwisko',

    '31': 'Filip Zych',

    '25': 'Bartosz Rataj',
}

print(klasa_3AP)
print(osoba)

